name: Build extension

on:
  release:
    types: [prereleased]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v3
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install
      - uses: lannonbr/vsce-action@master
        name: Create new Github release
        with:
          args: "package"
      - name: package-version
        run: node -p -e '`PACKAGE_VERSION=${require("./package.json").version}`' >> $GITHUB_ENV
      - name: Changelog
        id: changelog
        uses: mindsers/changelog-reader-action@v2.0.0
      - name: Create Release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: v${{ env.PACKAGE_VERSION }}
          artifacts: "*.vsix"
          body: ${{ steps.changelog.outputs.changes }}
          draft: false
          allowUpdates: true
          prerelease: true
          replacesArtifacts: true
      - uses: lannonbr/vsce-action@master
        with:
          args: "publish -p $VSCE_TOKEN --pre-release"
        env:
          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
      - name: publish to Open VSX
        run: npx ovsx publish -p $OVSX_TOKEN --pre-release
        env:
          OVSX_TOKEN: ${{ secrets.OVSX_TOKEN }}
